### ISSUE TITLE
I18n translate helper with automatic scope

### ISSUE THREAD

**Issue by Odaeus** [drapergem/draper#109]
In my views I almost always use the auto-scoped syntax of I18n.translate:

```
t(".my_account")
```

Putting this in a decorator method fails with `Cannot use t(".my_account") shortcut because path is not available`.

Should I scope all my keys explicitly from within Decorators or should Draper support automatic scoping based on the current view?

The latter seems to be slightly tricky to implement as the key is derived from an instance variable, `@virtual_path`, in [the ActionView TranslationHelper](https://github.com/rails/rails/blob/master/actionpack/lib/action_view/helpers/translation_helper.rb#L71) which seems to be set in [the Template](https://github.com/rails/rails/blob/master/actionpack/lib/action_view/template.rb#L123). I'm not sure how the variable is shared between them or how it could be accessed from Draper.

**Comment by lunij** [comment]
It seems the solution is not completely I18n compliant.

```ruby
class ExampleBase < ActiveRecord::Base
end

class ExampleSpecific < ExampleBase
end
```

If you now want the `ExampleSpecificDecorator` to do something relative like `h.t('.something'`, then the `virtual_path` is resolved using the `ExampleBase` class, instead of the `ExampleSpecific` class.

**Example:** When you are rendering the `show` view of `ExampleSpecific`, the `@virtual_path + key` is resolved to: 

_actual:_ `{locale}.example_bases.show.something`
_correct:_ `{locale}.example_specifics.show.something`

**Example:** When you are rendering the `cool_partial` partial of `ExampleSpecific`, the `@virtual_path + key` is resolved to:

_actual:_ `{locale}.example_bases.cool_partial.something`
_correct:_ `{locale}.example_specifics.cool_partial.something`
