### ISSUE TITLE
Does not work with mongoid

### ISSUE THREAD

**Issue by jpzwarte** [drapergem/draper#431]
``` ruby
  def self.setup_orm(base)
    base.class_eval do
      include Draper::Decoratable
    end
  end
```

Afaict the above code does not work because Mongoid::Document is not a class but a module. If you run "Mongoid::Document.ancestors" in a rails console, you see only Mongoid::Document, even after running the above code in the console. Draper::Decoratable is also not listed in an actual class that includes Mongoid::Document. Running the above code against a model _does_ give the desired result.

**Comment by Zorbash** [comment]
We came across this issue a rails engine. In our case an initializer interacts with some of the mongoid  models, causing autoloading and `Mongoid::Document` is included at that time. When  

```ruby
def self.setup_orm(base)
    base.class_eval do
      include Draper::Decoratable
    end
end
```
is called, `Mondoid::Document` gets `Draper::Decoratable` included. 
Due to ([ruby#10248](https://bugs.ruby-lang.org/issues/10248), [ruby#9112](https://bugs.ruby-lang.org/issues/9112)) the models won't be "updated" to respond to `decorate`.
