### ISSUE TITLE
ActiveJob Integration

### ISSUE THREAD

**Issue by hayesgm** [drapergem/draper#663]
Draper decorators do not currently implement [globalid](https://github.com/rails/globalid).  The fix is just to call in an initializer:

``` ruby
Draper::Decorator.send(:include, GlobalID::Identification) if defined?(GlobalID)
```

As `rails` includes `globalid` by default, would we want to add this line to the repo or put it in the documentation?

Without this fix, calling `UserMailer.welcome(user.decorate).deliver_later` will raise `ActiveJob:: SerializationError`, due to [this code](https://github.com/rails/rails/blob/31085a5cd47894b6fa397ca22fe8aa552d339ce8/activejob/lib/active_job/arguments.rb#L51).

**Comment by mikedao** [comment]
Modifying the documentation allows for an extremely quick fix. What are your arguments for/against?

**Comment by EtienneDepaulis** [comment]
This fix might be misleading. It works great to to silence the `ActiveJob:: SerializationError` but as it retrieves the object from DB again later, the object is not decorated anymore, thus preventing from using added methods in the emails.

**Comment by codebycliff** [comment]
While this might be misleading, you should still be able to pass a decorated object to a background job without it blowing up. Ideally, a decorated object should behave as if it were the object it is decorating. Here's what I'm proposing:

1. Add: `include GlobalID::Identification if defined? GlobalID` to `Draper::Decorator` so that it doesn't blow up.
2. Add some documentation to the README saying: "While you can pass a decorated object to background jobs, the object won't be decorated when it is deserialized."

Is anyone opposed to this solution?

**Comment by codebycliff** [comment]
Closing this as I believe it is resolved. If someone figures out how to deserialize the record as a _decorated_ object, feel free to open a pull request.
