### ISSUE TITLE
Destructive decorator (decorate!)

### ISSUE THREAD

**Issue by sintro** [drapergem/draper#701]
Hello! Is there any way to make some overrides to AR model to make it possible to do something like:

```
def show
  @user.decorate!
end
```

So there is no need to write anything else. This can be useful if I am getting @user from before_filter but for some reasons don't want to decorate it in every action, for example.

**Comment by lucianosousa** [comment]
First question: Why can you not decorate your `user` in a before filter?
I mean, there is no reason to avoid this.

**Comment by sintro** [comment]
To be honest, I can find only one argument now why I should avoid it: I am using CanCanCan gem for authorization, and by default it does automatic resource loading with the filters I specify in Abilities class. It is handy, because I have a lot of roles in my application and it takes the resource loading routine. If I will do before_filter, which will do something like @user = User.find(:id), CanCanCan will not load resource automatically.

**Comment by lucianosousa** [comment]
I really suggest you try a solution like this:
https://github.com/anlek/draper-cancan

Or, write your own helper methods to allow you use the `UserDecorator` for this purpose.

You can have a big problem in the future with a lot of unused methods in your Decorator just because you ignore it in few parts, or duplicate this code in another place.

What you need to do is just what this gem is doing, so, even if you need write a piece of new code, it's better than ignore the decorator.

Think about it.


btw, if you want to instantiate a `Decorator` in some part of your code, you can do somethink like:
```
def show
  UserDecorator.new(self)
end
```

I think it works but again, I do not recommend it.

**Comment by sintro** [comment]
Actually, this gem is too old and is solving not exactly the problem I am facing with. I need not only User model wrapping with decorate method, but this gem is about it - to solve the problem of potential bug with "can?" method, used on decorated User model. What I need it to create the decorated instances of various models by executing some king of destructive method on AR class. I already tried to user "append_before_filter", didn't work.
 May be I should open such issue on CanCanCan hub.

**Comment by anlek** [comment]
@sintro this might be way too late for you but maybe this is what you're looking for: https://github.com/GoodMeasuresLLC/draper-cancancan?

**Comment by anlek** [comment]
I've added a note to `draper-cancan` to say it's no longer recommended.
