### ISSUE TITLE
undefined method `includes' for #<Draper::CollectionDecorator:0x007fa8f21c0ed8>

### ISSUE THREAD

**Issue by adsteel** [drapergem/draper#702]
I am having a similar problem to [this issue](https://github.com/drapergem/draper/issues/683). After calling `delegate_all` in my delegator, and decorating that records' associations, I am unable to call ActiveRecord's `includes`.

``` ruby
class AuthorDecorator < Draper::Decorator
  delegate_all
  decorates_association :posts
  ...
end

class BlogDecorator < Draper::Decorator
  delegate_all
  ...
end

@author.decorate.posts.includes(:comments)

# raises NoMethodError
# undefined method `includes' for #<Draper::CollectionDecorator:0x007fa8f21c0ed8>
```

This is a simplified example, and calling `.decorate` after the `.includes` isn't an option.

**Comment by lucianosousa** [comment]
can you try:
`AuthorDecorator.new(@author).posts.includes(:comments)`

and see what is happening?

**Comment by adsteel** [comment]
Sure. That returns the same error. Thanks for your quick response!

**Comment by Mohit-Pawar** [comment]
hi @adsteel can you try this.

class AuthorDecorator < Draper::Decorator
  delegate_all
  decorates_association :posts, with: PostsDecorator
  ...
end
class PostsDecorator < Draper::CollectionDecorator
	delegate :includes
end
or
@author.decorate.posts.object.includes(:comments) 
this option is not ideal

**Comment by adsteel** [comment]
@Mohit-Pawar Thanks, I had put this feature on hold, but I'll try that when it starts up again. Do you know why includes isn't automatically delegated with `delegate_all` ?

**Comment by Mohit-Pawar** [comment]
@adsteel 
The main reason why includes isn't automatically delegated with delegate_all is we are 
delegating all methods for AuthorDecorator not Draper::CollectionDecorator
1).
@author.decorate.posts will return Draper::CollectionDecorator Object
but Draper::CollectionDecorator delegates only following methods.

array_methods = Array.instance_methods - Object.instance_methods
delegate :==, :as_json, *array_methods, to: :decorated_collection
see source draper/lib/draper/collection_decorator.rb line 18

that is why @author.decorate.posts.first will work and @author.decorate.posts.includes(:comments) will not

But,
Now By using below code.
decorates_association :posts, with: PostsDecorator

@author.decorate.posts will return Draper::PostsDecorator Object
and we are explicitly delegating includes method in Draper::PostsDecorator

2).
@author.decorate.posts.object returns ActiveRecord::Associations::CollectionProxy(the object with is decorated)
instead of Draper::CollectionDecorator
ActiveRecord::Associations::CollectionProxy has method includes defined

**Comment by adsteel** [comment]
@Mohit-Pawar That makes sense. I'm just wondering, since this is a Rails-specific gem, why wouldn't we have the option to delegate all CollectionProxy methods to CollectionDecorator objects?

**Comment by Mohit-Pawar** [comment]
what if we are using mongoid instead of active_record?

**Comment by adsteel** [comment]
That makes sense. Would it make sense to have helpers for various collections? `delegate_all_active_record` or something?

**Comment by Mohit-Pawar** [comment]
may be

**Comment by salomoko** [comment]
## This is how I handled it and it worked like a charm! 

**Models**
```
Message < ActiveRecord::Base
  has_many :comments
end
Comment < ActiveRecord::Base
  belongs_to :message, optional: true
end
```
**Decorators**
```
class MessageDecorator < ApplicationDecorator
  decorates_finders
  decorates_association :comment
  delegate_all
end

class CommentDecorator < ApplicationDecorator
  decorates_association :message
  delegate_all
end
```

**Controller usage**
```
class MessagesController < ApplicationController
  def show
    # decorated finders in MessageDecorator
    @message = MessageDecorator.find(params[:id])

    # @message is already decorated with a :comment association now it will respond_to?() AR methods
    @comment = @message.comments.build.decorate
    # thus @comments.decorated? == true
  end
end
```
**Question??** (@Mohit-Pawar, @adsteel)
_Why is it you called `.decorate` on the `@article` prior to accessing the associated posts?? Is the `@article` object not decorated yet?_

**Comment by codebycliff** [comment]
This should be fixed via https://github.com/drapergem/draper/pull/845.
