### ISSUE TITLE
.decorate on an ActiveRecord::Associations::CollectionProxy ignores current value

### ISSUE THREAD

**Issue by riffraff** [drapergem/draper#706]
This is probably related to https://github.com/drapergem/draper/issues/646, but my specific problem is with unpersisted objects, i.e. if there is an unsaved object in an association in the same example code (`user has_many posts`), we get

```
>> user.posts.build title: 'unsaved post'
... 
>> user.posts.map(&:name))
=> ["saved post", "unsaved post"]
>> user.posts.decorate.map(&:name))
=> ["saved post"]
```

This proves problematic when working with decorated values in nested forms, where if there is a validation error the form shows data as-is-in-db rather than as-is-in-this-page.

While there is a workaround (doing a `.map(&:decorate)` step explicitly), it seems like this is surprising behaviour, is it by design or accidental?

**Comment by Mohit-Pawar** [comment]
@riffraff 
 By design we should use Decorate Associated Objects and Collection Decorator

so if user has_many posts
we should create UserDecorator and PostsDecorator as follows.

class UserDecorator < Draper::Decorator
  delegate_all
  decorates_association :post, with: PostsDecorator
end

class PostsDecorator < Draper::CollectionDecorator
  delegate_all
end

so when you try
>> user.posts.build title: 'unsaved post'

>> user.posts.map(&:name))
=> ["saved post", "unsaved post"] => correct ouput no need to use .map(&decorate)
