### ISSUE TITLE
release 3.0

### ISSUE THREAD

**Issue by kbrock** [drapergem/draper#777]
Hello,

We're using Rails 5.0.x.
Draper 3.0.0pre1 supports version 5.0.x of rails. That is what we've been using since August 10, 2016.

Is there a road map to finally releasing draper 3.0? So rails 5.0 developers can point to a non-pre gem?

Thanks

**Comment by varyonic** [comment]
@seanlinsley is looking for new maintainers, anyone?  Everyone else appears to have moved on, ActiveAdmin is the only [dependent project](https://github.com/drapergem/draper/network/dependents) I know of.  @owen2345 at Camaleon CMS?

**Comment by toshimaru** [comment]
I'm waiting for new version!! Is anyone working for new version release?

**Comment by codebycliff** [comment]
@varyonic I don't know if I can commit to maintaining full time; however, I'd like to do what I can to help get 3.0.0 released and then go from there.  I'd hate to see such a useful gem die because we failed to provide support for Rails 5.

We have been running 3.0.0.pre1 in production with Rails 5 for several months now without issue. When attempting an upgrade to Rails 5.1, I had to point draper to master to get it to work. So it appears that master is compatible with Rails 5 and 5.1 to some extent.

@seanlinsley Are there specific issues you were hoping to get fixed before releasing version 3.0.0? If not, I propose we cut a release for 3.0.0 and fix reported issues from there. That way draper isn't a roadblock for upgrading Rails and people aren't tempted to just remove it from their project.

**Comment by syguer** [comment]
I want to help as I can 😄

**Comment by codebycliff** [comment]
Pull request open: https://github.com/drapergem/draper/pull/780

**Comment by codebycliff** [comment]
This release has been merged and push to RubyGems. Please report any issues you may come across.

**Comment by kenta-s** [comment]
Thank you for the great work! We were really looking forward to this release :)

Would you like to create 'a release' for 3.0.0 on GitHub as well? If so, this link might be useful as a reference: https://help.github.com/articles/creating-releases/

**Comment by seanlinsley** [comment]
A release on GitHub is automatically created if a version tag is created.

<img width="378" alt="screen shot 2017-05-08 at 9 28 14 pm" src="https://cloud.githubusercontent.com/assets/688886/25833233/4e2422be-3435-11e7-89a0-7fbf220a3761.png">

**Comment by codebycliff** [comment]
@kenta-s Sorry about that. I have created the corresponding Github release.
