### ISSUE TITLE
Should automatically clear view_context before/after each spec

### ISSUE THREAD

**Issue by zinkkrysty** [drapergem/draper#814]
So that it doesn't leak from a mailer spec to a controller spec and viceversa, since the helpers are different in those contexts.

This probably causes all these issues:
#523 #813 #655 #580

We need a solution that addresses these issues.

**Comment by codebycliff** [comment]
Thanks for reporting this issue. I have checked the issues you referenced and it does appear that they are all related. I will start looking into it, but I may need to gather some context from some of the original authors as to why we aren't doing this.

Furthermore, it looks like we are clearing the view context `before` each spec (https://github.com/drapergem/draper/blob/master/lib/draper/test/rspec_integration.rb). In one of the referenced issues, you said adding an `after` hook to clear the view context fixed it. I question why it is needed in both `before` and `after` hooks.

**Comment by mobject** [comment]
I am having same issue when running several mailers and the Context was not cleared out

**Comment by codebycliff** [comment]
@tibbon I was able to contact one of the original authors, but they couldn't remember enough context to be of any help. I have dug through all the related issues and put together a rough overview and timeline of the issue.

## Overview
While this issue seems to exist for both Minitest and RSpec, it seems to be more common with RSpec. I just merged a [pull request](https://github.com/drapergem/draper/pull/839) for the Minitest side of things that hopefully will clear up any remaining issues for Minitest. For the rest of this comment / issue, I'll focus on RSpec.

## Timeline
1. The first attempt to fix this issue was in 2013 and is [located here](https://github.com/drapergem/draper/commit/3d07cb387b1cae6f97897dfb85512e30f5e888e9). It started out as an `after(:each)` for `decorator`, `mailer` and `controller` specs.
1. A couple months later, [this issue](https://github.com/drapergem/draper/issues/523) was opened. A lot of great discussion came out of that issue.
    - The initial conversation lead to it being changed to a `before(:each)` [here](https://github.com/drapergem/draper/pull/547/files). This was still in 2013.
    - That issue continued to get conversation for a couple years, eventually leading to [a proposed solution](https://github.com/drapergem/draper/issues/523#issuecomment-314414888) of using **both** `before(:each)` and `after(:each)`.

## Proposed solution
I don't understand why you would need **both** `before(:each)` and `after(:each)`, but am at the point of just changing it to cover both. I think the only thing this could impact is _potentially_ slowing down the specs by a small amount. I feel the performance impacts would be most likely negligible, especially when comparing it to the time lost due to having to rebuild because of a flapping test.

Any thoughts?

**Comment by pgaspar** [comment]
Hello 👋 This seems to be happening to me as well in situations where `decorator`, `mailer` and `controller` specs are not the only ones using decorators. For example, if you have an asynchronous job class instantiating decorators (similar to what mailers do) you'll need to add `before(:each)` to those specs yourself.

Adding `after(:each)` to `decorator`, `mailer` and `controller` would help reduce the chance of problems, specially if there's only one other type of spec using decorators. But maybe this would be better solved with a documentation change 🤔

**Comment by pgaspar** [comment]
@codebycliff thanks. That looks good :+1:

**Comment by codebycliff** [comment]
I updated the documentation in https://github.com/drapergem/draper/pull/847. If we continue to get issues opened up around this, I'll come back and clear the view context before _every_ test.
