### ISSUE TITLE
Calling decorate on a STI model returns a decorator for its parent

### ISSUE THREAD

**Issue by terencedignon** [drapergem/draper#815]
Draper: 3.0.0
Rails: 5.0.3

I'm running into issues with calling .decorate on STI models.  For instance, I have a User model from which an Employer inherits.  Calling .decorate on Employer returns:
```
Draper::UninferrableDecoratorError: Could not infer a decorator for ActiveRecord::Base.
from /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/draper-3.0.0/lib/draper/decoratable.rb:82:in `rescue in decorator_class'
```
It hits prefix assignment:

```
      def decorator_class
        prefix = respond_to?(:model_name) ? model_name : name
         ...
      end
```

respond_to?(:model_name) then returns true and the class is assigned to the following model_name:
```
[2] pry(main)> Employer.model_name
=> #<ActiveModel::Name:0x007fbe9a070a98
 @collection="users",
 @element="user",
 @human="User",
 @i18n_key=:user,
 @klass=Employer (call 'Employer.connection' to establish a connection),
 @name="User",
 @param_key="user",
 @plural="users",
 @route_key="users",
 @singular="user",
 @singular_route_key="user">
```

All in all, it ends up returning the parent model, UserDecorator, rather than the desired EmployerDecorator.

Let me know if I'm missing something!

If not, I believe there should be a more nuanced check in decorator_class that infers a STI and returns the proper decorator.

**Comment by codebycliff** [comment]
Thanks for reporting the issue. This functionality should be possible and I've had it work for me in the past. The inference the gem does results in this kind of thing from time to time.

If you have a sample app that reproduces the issue, that would help speed things up tremendously. Otherwise, give me a little bit of time to try and reproduce it.

**Comment by terencedignon** [comment]
Hi Cliff, thanks for the quick response! Here's a barebones example that reproduces the issue:  https://github.com/terencedignon/draper_issue-815

**Comment by terencedignon** [comment]
This is a solution that seems to work for us: https://github.com/terencedignon/draper/commit/d76236fa644f7237c6255e21a1dbfc2b595e7c36

**Comment by codebycliff** [comment]
I've taken a look at your reproduction app and the stack overflow post you referenced. I have confirmed that this is due to you monkey patching `model_name`. Unfortunately, there is nothing I can do to help as Draper is doing everything correctly. We are inferring the decorator based on the `model_name`, which you are overriding to force it to return a `ActiveModel::Name` instance that corresponds with the `User` model.

I wouldn't recommend this kind of a monkey patch on the `model_name` method. I think there are better ways to go about this. For instance,

1. Use the `becomes` method to force a downcast. This results in things like `link_to 'View', employer.becomes(User)`. This could become very tedious, as you will have to modify all the `link_to`, `redirect_to`, etc. in your codebase (probably what you were trying to avoid in the first place).

2. Map your subclass resources to the parent resources in `routes.rb`. For example:

```ruby
map.resources :employers, controller: 'users'
```

The stackoverflow article referenced mentioned this working for `link_to` and `redirect_to`, but not `form_for`. If you are on Rails 5.1 or greater, you can use the new `resolve` method to solve the `form_for`. It was designed for exactly what you are trying to do (i.e. resolve a class to another class for routing purposes).

I would recommend option number 2. I think that would solve your issues and Draper would go back to working for you. If none of these options work for you, you can just monkey patch draper with the solution above. However, I don't recommend this as I'm not entirely sure what other things this might affect.

Let me know if there is anything else I can help with.

**Comment by codebycliff** [comment]
Another option I didn't mention above is to override `model_name` in the rest of your subclass models. For example:

```ruby
class Employer < User
  def self.model_name
    ActiveModel::Name.new(self, nil, 'Employer')
  end
end
```

For what it's worth, I still recommend the second option from above.

**Comment by codebycliff** [comment]
I'm going to close this for now. Let me know if this didn't solve your problem or you think more is going on and I'll re-open the issue.
