### ISSUE TITLE
Clearing Draper::ViewContext in RSpec

### ISSUE THREAD

**Issue by mapreal19** [drapergem/draper#837]
I had an issue with some specs not clearing the ViewContext and hence having `undefined h.current_user`. It doesn't make sense to clear for every type of spec?

https://github.com/drapergem/draper/blob/ed62f5555148b997eeb9feb365dd3dffcdb3d903/lib/draper/test/rspec_integration.rb#L12

**Comment by codebycliff** [comment]
The issue you are experiencing is actually due to the view context _not_ being cleared after certain spec types. See the documentation in [this pull request](https://github.com/drapergem/draper/pull/847), as well as the [referenced issue](https://github.com/drapergem/draper/issues/814) for more detail. Are you using decorators inside of jobs? That would be a scenario where the view context was built without `current_user` accessible and subsequent tests would fail.

**Comment by mapreal19** [comment]
Not using decorators inside jobs but it was a similar scenario. Thanks for the PR! I'll be useful for others.

**Comment by codebycliff** [comment]
Perfect. Glad we could help.
