### ISSUE TITLE
Create unique context for each item in a collection?

### ISSUE THREAD

**Issue by samstickland** [drapergem/draper#883]
We have an unusual use cache where having this functionality would be useful to us:

```
module Draper
  class CollectionDecorator
    module UniqueContext
      def decorate_item(item)
        item_decorator.call(item, context: context.clone)
      end
    end

    prepend UniqueContext
  end
end
```

As you can see we've currently monkey patched. Would there be any interest in a PR?

**Comment by Alexander-Senko** [comment]
> We have an unusual use cache…

I agree that it's not a common case. That's why pulling this in seems unreasonable. It will slow down every one else's code and increase memory footprint for no reason.

Moreover, a _context_ that's not shared seems counter intuitive for me 🤔 It looks like you want it to modified on per item basis that makes it something more than a collection context, IMO.

**Comment by samstickland** [comment]
That's a fair comment. It's been over 4 years since I raised this and with four more years of experience mutating the context doesn't seem right to me either
